import Link from "next/link";
import type { Metadata } from "next";
import { buildDigest, topStories, type Digest } from "@/lib/digest";
import { SOURCE_LABELS } from "@/lib/types";
import { hostname } from "@/lib/format";

export const revalidate = 3600;

export const metadata: Metadata = {
  title: "Daily Digest — Cometry",
  description:
    "The day's top developer stories, summarized. Why each one matters, in one line.",
};

export default async function DigestPage() {
  let digest: Digest | null = null;
  let fallback: Awaited<ReturnType<typeof topStories>> = [];
  try {
    digest = await buildDigest();
    if (!digest) fallback = await topStories();
  } catch {
    fallback = await topStories();
  }

  return (
    <main className="mx-auto w-full max-w-2xl flex-1 px-4 py-8">
      <div className="mb-6">
        <Link
          href="/"
          className="text-sm text-zinc-500 hover:text-zinc-300"
        >
          ← Back to feed
        </Link>
        <h1 className="mt-3 text-2xl font-bold tracking-tight">
          Daily Digest
        </h1>
        {digest ? (
          <p className="mt-2 text-zinc-400">{digest.intro}</p>
        ) : (
          <p className="mt-2 text-sm text-zinc-500">
            Today&apos;s top developer stories, ranked.
          </p>
        )}
      </div>

      <ol className="flex flex-col gap-4">
        {(digest ? digest.items : fallback.map((story) => ({ story, blurb: null }))).map(
          ({ story, blurb }, index) => (
            <li
              key={story.id}
              className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-4"
            >
              <div className="flex gap-3">
                <span className="text-lg font-bold tabular-nums text-zinc-700">
                  {index + 1}
                </span>
                <div className="min-w-0">
                  <div className="mb-1 flex flex-wrap items-center gap-2 text-xs text-zinc-500">
                    <span className="font-medium text-cyan-400">
                      {SOURCE_LABELS[story.source]}
                    </span>
                    {hostname(story.url) && <span>{hostname(story.url)}</span>}
                    <span>· ▲ {story.score}</span>
                  </div>
                  <a
                    href={story.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="font-semibold leading-snug text-zinc-100 hover:text-cyan-400"
                  >
                    {story.title}
                  </a>
                  {blurb && (
                    <p className="mt-1.5 text-sm leading-snug text-zinc-400">
                      {blurb}
                    </p>
                  )}
                </div>
              </div>
            </li>
          )
        )}
      </ol>

      {digest && (
        <p className="mt-6 text-center text-xs text-zinc-600">
          Summaries generated by AI · refreshed hourly
        </p>
      )}
    </main>
  );
}
